set nocp
filetype off

set rtp+=/usr/share/vim/vim74/bundle/Vundle.vim
call vundle#begin('/usr/share/vim/vim74/bundle')
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'mattn/emmet-vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'StanAngeloff/php.vim'
Plugin 'vim-scripts/tComment'
Plugin 'tomtom/tlib_vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'vim-airline/vim-airline'
Plugin 'jwalton512/vim-blade'
Plugin 'schickling/vim-bufonly'
Plugin 'skammer/vim-css-color'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'qbbr/vim-twig'
Plugin 'digitaltoad/vim-pug'
Plugin 'crusoexia/vim-monokai'
Plugin 'octol/vim-cpp-enhanced-highlight'
call vundle#end()
filetype plugin indent on

" gVim remove toolbars and scrolls, set console size
" set guioptions-=m
" set guioptions-=T
" set guioptions-=r
" set guioptions-=L
" set guifont=Consolas:h14
" set lines=40 columns=130

set fillchars+=stl:\ ,stlnc:\
set laststatus=2
set mouse=r
set nospell
set t_Co=256
set cursorcolumn
set cursorline 
set pastetoggle=<F2>
set relativenumber
set number
set virtualedit=onemore
set history=9999
set splitbelow
set splitright
set pastetoggle=<F2>
set mouse=a
set autowrite
set showmode
set showcmd
set wrap
set equalalways
set wildmenu
set autoread
set wildmode=list:longest,full
set gdefault
set expandtab
set shiftwidth=2
set softtabstop=2
set foldmethod=manual
set ignorecase
set hlsearch
set fileencoding=utf-8
set encoding=utf-8
set backspace=indent,eol,start
set smartcase
set incsearch
set showmatch
set winheight=10
set nolist
set noswapfile
set visualbell
set colorcolumn=80
set noesckeys
set clipboard=unnamedplus
syntax on
colorscheme monokai

let g:user_emmet_mode='a'
let g:user_emmet_leader_key='<C-y>'
let g:airline_symbols = {}
let g:airline_powerline_fonts=0
let g:airline_symbols_ascii = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline_section_warning=''
let g:airline_left_sep = ''
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_right_sep = ''
let g:airline_symbols.crypt = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.paste = ''
let g:airline_symbols.paste = ''
let g:airline_symbols.paste = ''
let g:airline_symbols.spell = ''
let g:airline_symbols.notexists = ''
let g:airline_symbols.whitespace = ''
let g:airline#extensions#tabline#enabled=1
let g:airline_highlighting_cache = 1
let g:ctrlp_show_hidden=1
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = '\v[\/](node_modules|bower_components|vendor)$'
let g:NERDTreeMinimalUI=1
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1
let g:NERDTreeWinSize=35
let NERDTreeQuitOnOpen=0
let bclose_multiple = 0
let mapleader="\<Space>"
let b:vcm_tab_complete = 'dict'

autocmd StdinReadPre * let s:std_in=1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-h> <C-w><C-h>
imap <C-v> <ESC>"+pi
imap <C-J> <Plug>snipMateNextOrTrigger
smap <C-J> <Plug>snipMateNextOrTrigger
map <C-v> "+p
map <C-c> "+y
map <Tab> <Nop>
map <leader>k :NERDTreeTabsToggle<CR>:vertical resize 35<CR>
map <leader>m :NERDTreeTabsFind<CR>
map <leader>1 :vertical resize 30<CR>
map <leader>2 :vertical resize 55<CR>
map <leader>3 :vertical resize 80<CR>
map <leader>x :split<CR>
map <leader>z :vsplit<CR>
map <leader>n :nohl<CR>
map <leader>h :tabprevious<CR>
map <leader>l :tabnext<CR>
map <leader>t :tabnew<CR>
map <leader>a :bprevious<CR>
map <leader>f :bnext<CR>
map <leader>w :tabclose!<CR>
map <leader>W :NERDTreeTabsClose<CR>:bufdo bd!<CR>
map <leader>e :tabonly<CR> :BufOnly!<CR>
map <leader>s :execute "tabmove" tabpagenr() - 2 <CR>
map <leader>d :execute "tabmove" tabpagenr() + 1 <CR>
map <C-Up> ddkkp
map <C-Down> ddp
map <C-a> ggvG$
map <C-x> "+ygvd
map <C-g> :vimgrep 
map <C-b> :Bookmark 
map <C-o> 8<C-w><
map <C-i> 8<C-w>>
map < <gv
map > >gv
map = :vertical resize +5 <CR>
map - :vertical resize -5 <CR>
map <C-d> <C-d>zz
